version: '3'
services:
  node-app:
    container_name: express-node-app-container
    ports:
      - "3000:3000"
    env_file:
      - ./.env
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root