version: '3'
services:
  node-app:
    container_name: express-node-app-container
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
  redis:
    image: redis
volumes:
  mysql-db:
